ALTER TABLE "Challenges"
  ADD COLUMN IF NOT EXISTS claimed_by uuid NULL,
  ADD COLUMN IF NOT EXISTS claimed_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS claim_status text NOT NULL DEFAULT 'open',
  ADD COLUMN IF NOT EXISTS ai_category_confidence numeric NULL;

CREATE TABLE IF NOT EXISTS challenge_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id bigint NOT NULL REFERENCES "Challenges"(id) ON DELETE CASCADE,
  collaborator_id uuid NOT NULL,
  claimed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (challenge_id)
);

CREATE OR REPLACE FUNCTION claim_challenge(p_challenge_id bigint, p_collaborator_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_claimed_by uuid;
BEGIN
  SELECT claimed_by INTO v_claimed_by
  FROM "Challenges"
  WHERE id = p_challenge_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'message', 'Challenge not found');
  END IF;

  IF v_claimed_by IS NOT NULL THEN
    IF v_claimed_by = p_collaborator_id THEN
      RETURN json_build_object('success', true, 'already_claimed', true, 'message', 'You already claimed this challenge');
    END IF;
    RETURN json_build_object('success', false, 'message', 'Challenge has already been claimed');
  END IF;

  UPDATE "Challenges"
  SET claimed_by = p_collaborator_id,
      claimed_at = now(),
      claim_status = 'claimed',
      participants = COALESCE(participants, 0) + 1
  WHERE id = p_challenge_id;

  INSERT INTO challenge_claims (challenge_id, collaborator_id)
  VALUES (p_challenge_id, p_collaborator_id);

  RETURN json_build_object('success', true, 'already_claimed', false, 'message', 'Challenge successfully claimed');
END;
$$;
